name: Icon1

env:
    DOCKER_BUILDKIT: 1

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    create:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+*'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build_node:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set Branch
                id: vars
                run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
                    registry-url: 'https://registry.npmjs.org'

            -   name: Cache CI node_modules
                uses: actions/cache@v2
                env:
                    cache-name: cache-node-modules
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}

            -   name: Build App
                #env:
                run: |
                    npm ci
                    npm run bootstrap && npm run hoist
                    npm test
                    npm run build

            -   name: Send code coverage report to Codecov.io
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}

            -   name: Publish to NPM
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    ./deploy.sh
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
